Первая версия
unterumarmung/GoatAndCabbageGame pull request #1
Opened 2020-04-30 08:23 UTC by unterumarmung

2020-04-30 20:40 UTC, gvterechov requested changes

2020-04-30 20:40 UTC, gvterechov commented on src/main/java/model/Cell.java
> +    public Direction isNeighbor(@NotNull Cell cell) {
думаю что будет лучше neighborDirection

2020-04-30 20:40 UTC, gvterechov commented on src/main/java/model/Cell.java
> +        objects.add(object);
в ячейку можно добавить объект, установленный в другую ячейку

2020-04-30 20:40 UTC, gvterechov commented on src/main/java/model/Cell.java
> +        objects.remove(object);
на диаграмме классов композиция, однако при удалении объекта из ячейки связь не разрывается с обеих сторон

2020-04-30 20:40 UTC, gvterechov commented on src/main/java/model/Cell.java
> +        if (cell.neighborCell(direction.opposite()) == null) {
вероятно, условие в таком виде лишнее. соседа у `cell` стоит устанавливать принудительно, если это не `this`, даже если он был задан

2020-04-30 20:46 UTC, unterumarmung commented on src/main/java/model/Cell.java
> +        if (cell.neighborCell(direction.opposite()) == null) {
Сделал по стопам Носкина. Исключение кажется здесь более логичным, потому что если мы попытались перезаписать соседа - то что-то явно не так пошло.

2020-04-30 20:56 UTC, unterumarmung commented on src/main/java/model/Cell.java
> +        objects.remove(object);
Композиция только для стены и капусты. Там связь не может разорваться. Наверное стоит другой вариант использовать.
С козой там агрегация.

2020-04-30 20:57 UTC, unterumarmung commented on src/main/java/model/Cell.java
> +    public Direction isNeighbor(@NotNull Cell cell) {
Ок

2020-04-30 20:57 UTC, unterumarmung commented on src/main/java/model/Cell.java
> +        objects.add(object);
Ок, исправлю

2020-05-07 05:13 UTC, gvterechov requested changes

2020-05-07 05:13 UTC, gvterechov commented on src/main/java/model/Cell.java
> +        objects.remove(object);
у Носкина для этих целей есть отдельные геттеры/сеттеры для разного типа объектов

2020-05-07 05:24 UTC, gvterechov approved these changes

2020-05-07 05:29 UTC, merged